### ISSUE TITLE
Hope to support custom output capture

### ISSUE THREAD

**Issue by victor-vb** [fosskers/linya#12]
For example, it may be used in xterm in the browser environment,For example, maybe it is used in xterm in the browser environment, so that the input can be captured and sent to the front end.

**Comment by fosskers** [comment]
To clarify, are you hoping to be able to capture `stderr` in some way? That's what `linya` outputs its bars to.

**Comment by victor-vb** [comment]
Yes, hopefully in a non-standard cli environment, but they have the same standard execution display method

**Comment by fosskers** [comment]
Can you describe that environment a little more?

**Comment by victor-vb** [comment]
The front-end uses the react framework and is an executable program packaged with tauri. One of the xterm front-end libraries has already done some conventional command line work for us.
![image](https://github.com/fosskers/linya/assets/113876742/676415ba-4888-40fe-bd41-6b99a9d6984a)
![image](https://github.com/fosskers/linya/assets/113876742/3b5fd45d-e034-4ebe-a123-0744e1ab1722)
Maybe I just need to capture the progress of the back-end work and then output the progress bar to the front-end, and the progress bar will be displayed naturally.

**Comment by victor-vb** [comment]
Then I have to separate two programs and use piped to capture stderr and stdout. Maybe I can try this difficult integration solution.

**Comment by fosskers** [comment]
Don't you already have two programs, the frontend and the backend? 

Also keep in mind that `linya` depends on being able to see ANSI terminal codes to move the cursor around the screen. I'm not sure what that would do in a browser-based application.

**Comment by victor-vb** [comment]
Although there is a front end and a back end, they are one program. Maybe I can make a separate program and use piped to capture stdout and stderr. I will try it myself first.

**Comment by fosskers** [comment]
Let me know how it goes :+1:
