### ISSUE TITLE
Library panics with integer multiplication overflow on `armv7l`

### ISSUE THREAD

**Issue by Holzhaus** [fosskers/linya#7]
I'm using this library to show download progress, but it crashes on `armv7l`:

```
thread 'main' panicked at 'attempt to multiply with overflow', /home/user/.cargo/registry/src/github.com-1285ae84e5963aae/linya-0.2.1/src/lib.rs:232:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The file size is 83481243 (~80 MB), and apparently the result doesn't fit into an `usize` on that platform. It works on x86_64 though.

**Comment by fosskers** [comment]
As annoying as bugs like this are, these reports make me happy. Thanks for bringing this to my attention, I'm going to fix it tomorrow.

**Comment by fosskers** [comment]
Once I put a PR up, would you be available to help test it to make sure the fix actually works?

**Comment by Holzhaus** [comment]
> Once I put a PR up, would you be available to help test it to make sure the fix actually works?

Sure, thanks.

**Comment by fosskers** [comment]
There, can you give that a try?
